version: '3'
services:
  db:
    image: postgres:10.5
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: tamagotchi-basic-mechanics
      POSTGRES_PASSWORD: postgres
    volumes:
    - "postgres-data:/var/lib/postgresql/data"
  adminer:
    image: adminer:4
    restart: always
    ports:
    - 9999:8080
volumes:
  postgres-data:
    driver: local
