version: '3'
services:
  db:
    image: makar1031/tamagotchi-postgres:1.0.0
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      DB_BASE: base
      DB_AUTH: auth
      DB_COMPETITION: competition
    volumes:
    - "postgres-data:/var/lib/postgresql/data"
  adminer:
    image: adminer:4
    restart: always
    ports:
    - 9999:8080
volumes:
  postgres-data:
    driver: local
