spring:
  application:
    name: tamagochi-basicmechanics
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/tamagochi-basic-mechanics
    username: ${db.username:postgres}
    password: ${db.username:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.connection.autocommit: true
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 8085
logging:
  level:
    ru.tamagotchi: DEBUG
jwt:
  key: ${jwt.key}
