version: '3'
services:
  web-client:
    image: makar1031/tamagotchi-web-client
    ports:
      - 80:80
    depends_on:
      - base-app
  base-app:
    image: makar1031/tamagotchi-basic-mechanics
    ports:
      - 8085:8085
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: base
      JWT_KEY: B2ABF96B2E47A757CC051D709993A89FB09019F9E8BE44EEB7B2BC43A4A19BEE
      COMPETITION_URL: http://competition-app
      TZ: Europe/Moscow
    depends_on:
      - db
  auth-app:
    image: itine/tamagotchi-authorization
    restart: always
    ports:
      - 5001:80
    environment:
      ConnectionStrings__LocalDB: Host=db;Port=5432;Database=auth;Username=postgres;Password=postgres;Pooling=true;
      AppInfo__SecretKey: B2ABF96B2E47A757CC051D709993A89FB09019F9E8BE44EEB7B2BC43A4A19BEE
      TZ: Europe/Moscow
    depends_on:
      - db
  competition-app:
    image: palicpiotr/tamagotchi.competition:latest
    ports:
      - 8090:80
    environment:
      ConnectionStrings__LocalDB: Host=db;Port=5432;Database=competition;Username=postgres;Password=postgres;Pooling=true;
      AppConfig__SecretKey: B2ABF96B2E47A757CC051D709993A89FB09019F9E8BE44EEB7B2BC43A4A19BEE
      AppConfig__AuthBaseUrl: http://auth-app/
      TZ: Europe/Moscow
    depends_on:
      - db
  db:
    image: makar1031/tamagotchi-postgres:1.0.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      DB_BASE: base
      DB_AUTH: auth
      DB_COMPETITION: competition
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 9999:8080
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - 'C:/Users/makar/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - 'grafana-data:/var/lib/grafana'
volumes:
  postgres-data:
    driver: local
  grafana-data:
    driver: local
