CREATE TABLE PETS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    OWNER_ID INT NOT NULL,
    HEALTH INT NOT NULL,
    HUNGER INT NOT NULL,
    REST INT NOT NULL,
    MOOD INT NOT NULL,
    LAST_HEALTH_INCREASE_TIME	TIMESTAMP	NOT NULL,
    LAST_HUNGER_INCREASE_TIME	TIMESTAMP	NOT NULL,
    LAST_REST_INCREASE_TIME	TIMESTAMP	NOT NULL,
    LAST_MOOD_INCREASE_TIME	TIMESTAMP	NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    LAST_SCHEDULE_APPLY_TIME TIMESTAMP NOT NULL,
    STATUS VARCHAR(10) NOT NULL
);
CREATE INDEX PETS_OWNER_ID_index ON PETS (OWNER_ID)
