CREATE TABLE PETS (
    ID BIGSERIAL PRIMARY KEY,
    OWNER_ID int NOT NULL,
    HEALTH int NOT NULL,
    HUNGER int NOT NULL,
    REST int NOT NULL,
    MOOD int NOT NULL,
    LAST_ACCESS_TIME TIMESTAMP,
    STATUS varchar(10) NOT NULL
);
CREATE INDEX PETS_OWNER_ID_index ON PETS (OWNER_ID)
