CREATE TABLE PETS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    OWNER_ID INT NOT NULL,
    HEALTH INT NOT NULL,
    HUNGER INT NOT NULL,
    REST INT NOT NULL,
    MOOD INT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    LAST_ACCESS_TIME TIMESTAMP NOT NULL,
    STATUS VARCHAR(10) NOT NULL
);
CREATE INDEX PETS_OWNER_ID_index ON PETS (OWNER_ID)
