DROP TABLE PETS;
DROP TABLE ACTIONS;

CREATE TABLE PETS
(
  ID                        BIGSERIAL PRIMARY KEY,
  NAME                      VARCHAR(100) NOT NULL,
  OWNER_ID                  INT          NOT NULL,
  HEALTH                    INT          NOT NULL,
  HUNGER                    INT          NOT NULL,
  REST                      INT          NOT NULL,
  MOOD                      INT          NOT NULL,
  LAST_HEALTH_INCREASE_TIME TIMESTAMP    NOT NULL,
  LAST_HUNGER_INCREASE_TIME TIMESTAMP    NOT NULL,
  LAST_REST_INCREASE_TIME   TIMESTAMP    NOT NULL,
  LAST_MOOD_INCREASE_TIME   TIMESTAMP    NOT NULL,
  CREATE_TIME               TIMESTAMP    NOT NULL,
  LAST_SCHEDULE_APPLY_TIME  TIMESTAMP    NOT NULL,
  STATUS                    VARCHAR(10)  NOT NULL,
  DISEASE_CODE              VARCHAR(20)
);
CREATE INDEX PETS_OWNER_ID_INDEX ON PETS (OWNER_ID);

CREATE TABLE INDICATORS
(
  ID          BIGINT PRIMARY KEY,
  CODE        VARCHAR(20) NOT NULL,
  ROOM_CODE   VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(100)
);
CREATE UNIQUE INDEX INDICATORS_CODE_UINDEX ON INDICATORS (CODE);
CREATE UNIQUE INDEX INDICATORS_ROOM_CODE_UINDEX ON INDICATORS (ROOM_CODE);

CREATE TABLE ACTIONS
(
  ID                   BIGSERIAL PRIMARY KEY,
  CODE                 VARCHAR(20)  NOT NULL,
  DESCRIPTION          VARCHAR(100) NOT NULL,
  MAIN_INDICATOR       BIGINT       NOT NULL,
  VALUE_1              INTEGER      NOT NULL,
  ADDITIONAL_INDICATOR BIGINT,
  VALUE_2              INTEGER,
  DISEASE_CODE         VARCHAR(20),
  CONSTRAINT ACTIONS_INDICATORS_MAIN_IND_FK FOREIGN KEY (MAIN_INDICATOR) REFERENCES INDICATORS (ID),
  CONSTRAINT ACTIONS_INDICATORS_ADD_IND_FK FOREIGN KEY (ADDITIONAL_INDICATOR) REFERENCES INDICATORS (ID)
);
CREATE UNIQUE INDEX ACTIONS_CODE_UINDEX ON ACTIONS (CODE);
